<?php

$aLang = array(
    'charset'                                   => 'UTF-8',
    'PAYPAL_RATEPAY_LEGAL' => 'Mit Klicken auf den Button akzeptieren Sie die <a target="_blank" href="https://www.ratepay.com/legal-payment-terms" rel="noopener noreferrer">Ratepay Zahlungsbedingungen</a> und erklären sich mit der Durchführung einer <a  target="_blank" href="https://www.ratepay.com/legal-payment-dataprivacy" rel="noopener noreferrer">Risikoprüfung durch Ratepay</a>, unseren Partner,  einverstanden. Sie akzeptieren auch PayPals <a  target="_blank" href="https://www.paypal.com/de/webapps/mpp/ua/privacy-full?locale.x=de_DE" rel="noopener noreferrer">Datenschutzerklärung</a>. Falls Ihre Transaktion per Kauf auf Rechnung erfolgreich abgewickelt werden kann, wird der Kaufpreis an Ratepay abgetreten und Sie dürfen nur an Ratepay überweisen, nicht an den Händler.',
    'PAYPAL_ERROR_PAYEE_NOT_ENABLED_FOR_PUI_PROCESSING' => 'Aus technischen Gründen können wir im Moment leider keinen Rechnungskauf anbieten, bitte wählen Sie eine andere Zahlungsart. (PUI_NOT_ENABLED)',
    'PAYPAL_ERROR_PAYMENT_SOURCE_INFO_CANNOT_BE_VERIFIED' => 'Die Kombination aus Ihrem Namen und Ihrer Anschrift konnte nicht validiert werden. Bitte korrigieren Sie Ihre Daten und versuchen Sie es erneut. Weitere Informationen finden Sie in den Ratepay <a href="https://www.ratepay.com/legal-payment-dataprivacy/?lang=de" target="_blank" rel="noopener noreferrer" >Datenschutzbestimmungen</a> oder nutzen Sie das Ratepay <a href="https://www.ratepay.com/kontakt/" target="_blank" rel="noopener noreferrer">Kontaktformular</a>.',
    'PAYPAL_ERROR_PAYMENT_SOURCE_DECLINED_BY_PROCESSOR' => 'Die gewählte Zahlungsart kann nicht genutzt werden. Diese Entscheidung basiert auf einem automatisierten Datenverarbeitungsverfahren. Weitere Informationen finden Sie in den Ratepay <a href="https://www.ratepay.com/legal-payment-dataprivacy/?lang=de" target="_blank" rel="noopener noreferrer" >Datenschutzbestimmungen</a> oder nutzen Sie das Ratepay <a href="https://www.ratepay.com/kontakt/" target="_blank" rel="noopener noreferrer">Kontaktformular</a>.',
    'PAYPAL_PUI_REFERENCE' => 'Verwendungszweck'
);
