[{$smarty.block.parent}]
[{if $editable}]
    [{if $oViewConf->showPayPalMessageInBasket() }]
        [{include file="page/checkout/inc/paypal_message.tpl"}]
    [{/if}]
    [{if $oViewConf->showPayPalButtonInBasket()}]
        [{include file="page/checkout/inc/paypal_express_button.tpl" sButtonPosition="totals"}]
    [{/if}]
[{/if}]