[{$smarty.block.parent}]
[{assign var="blCanBuy" value=true}]
[{if $aVariantSelections && $aVariantSelections.selections}]
    [{assign var="blCanBuy" value=$aVariantSelections.blPerfectFit}]
    [{if !$blHasActiveSelections}]
        [{if !$blCanBuy && !$oDetailsProduct->isParentNotBuyable()}]
            [{assign var="blCanBuy" value=true}]
        [{/if}]
    [{/if}]
[{/if}]
[{if $oViewConf->showPayPalButtonInDetails()}]
    [{oxscript include=$oViewConf->getModuleUrl('agpaypal', 'out/js/paypal-button.js')}]
    [{if $blCanBuy}]
        [{include file="page/details/inc/paypal_button.tpl"}]
    [{/if}]
[{/if}]